version: "2"

checks:
  # Functions or methods with a high number of return statements. This is disabled because Go encourages early returns.
  return-statements:
    enabled: true
    config:
      threshold: 6
  similar-code:
    enabled: true
    config:
      # mass threshold for duplication analysis, default for Go is 100:  https://docs.codeclimate.com/docs/duplication#per-language-mass-threshold-defaults
      threshold: 120

plugins:
  gofmt:
    enabled: true
  govet:
    enabled: true
    checks:
      GoVet/BugRisk:
        enabled: false
  golint:
    enabled: false

exclude_paths:
  - "mocks/"
