// Code generated by mockery v2.9.4. DO NOT EDIT.

package m3connector

import mock "github.com/stretchr/testify/mock"

// KafkaProvider is an autogenerated mock type for the KafkaProvider type
type KafkaProvider struct {
	mock.Mock
}

// CreateACL provides a mock function with given fields: topic, username, permission
func (_m *KafkaProvider) CreateACL(topic string, username string, permission string) error {
	ret := _m.Called(topic, username, permission)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(topic, username, permission)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateTopic provides a mock function with given fields: topic, retentionMs
func (_m *KafkaProvider) CreateTopic(topic string, retentionMs int64) error {
	ret := _m.Called(topic, retentionMs)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int64) error); ok {
		r0 = rf(topic, retentionMs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateUser provides a mock function with given fields: username
func (_m *KafkaProvider) CreateUser(username string) error {
	ret := _m.Called(username)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(username)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
