// Code generated by mockery v2.9.4. DO NOT EDIT.

package rawdatalog

import (
	rawdatalog "github.com/dolittle/platform-api/pkg/rawdatalog"
	mock "github.com/stretchr/testify/mock"
)

// Repo is an autogenerated mock type for the Repo type
type Repo struct {
	mock.Mock
}

// Write provides a mock function with given fields: topic, moment
func (_m *Repo) Write(topic string, moment rawdatalog.RawMoment) error {
	ret := _m.Called(topic, moment)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, rawdatalog.RawMoment) error); ok {
		r0 = rf(topic, moment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
