---
apiVersion: v1
kind: Service
metadata:
  annotations:
    dolittle.io/tenant-id: 453e04a7-4f9d-42f2-b36c-d51fa2c83fa3
    dolittle.io/application-id: 11b6cf47-5d9f-438f-8116-0d9828654657
    dolittle.io/microservice-id: 67113383-cf7e-4d8d-9891-9330f1683842
  labels:
    tenant: Customer-Chris
    application: Taco
    environment: Dev
    microservice: Webhook2
  name: dev-webhook2
  namespace: application-11b6cf47-5d9f-438f-8116-0d9828654657
spec:
  selector:
    tenant: Customer-Chris
    application: Taco
    environment: Dev
    microservice: Webhook2

  ports:
    - port: 80
      targetPort: 80
      name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    dolittle.io/tenant-id: 453e04a7-4f9d-42f2-b36c-d51fa2c83fa3
    dolittle.io/application-id: 11b6cf47-5d9f-438f-8116-0d9828654657
    dolittle.io/microservice-id: 67113383-cf7e-4d8d-9891-9330f1683842
  labels:
    tenant: Customer-Chris
    application: Taco
    environment: Dev
    microservice: Webhook2
  name: dev-webhook2
  namespace: application-11b6cf47-5d9f-438f-8116-0d9828654657
spec:
  selector:
    matchLabels:
      tenant: Customer-Chris
      application: Taco
      environment: Dev
      microservice: Webhook2
  template:
    metadata:
      annotations:
        dolittle.io/tenant-id: 453e04a7-4f9d-42f2-b36c-d51fa2c83fa3
        dolittle.io/application-id: 11b6cf47-5d9f-438f-8116-0d9828654657
        dolittle.io/microservice-id: 67113383-cf7e-4d8d-9891-9330f1683842
      labels:
        tenant: Customer-Chris
        application: Taco
        environment: Dev
        microservice: Webhook2
    spec:
      imagePullSecrets:
        - name: acr
      containers:
      - name: head
        image: 453e04a74f9d42f2b36cd51fa2c83fa3.azurecr.io/dolittle/platform/platform-api:dev-x
        imagePullPolicy: Always
        args: [
          "raw-data-log",
          "server"
        ]
        ports:
          - containerPort: 80
            name: http
        envFrom:
          - configMapRef:
              name: dev-webhook2-env-variables
          - secretRef:
              name: dev-webhook2-secret-env-variables
        volumeMounts:
          - mountPath: /app/data
            name: config-files

      volumes:
        - name: config-files
          configMap:
            name: dev-webhook2-config-files
