// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	platform "github.com/dolittle/platform-api/pkg/platform"
	storage "github.com/dolittle/platform-api/pkg/platform/storage"
	mock "github.com/stretchr/testify/mock"
)

// RepoCustomerTenants is an autogenerated mock type for the RepoCustomerTenants type
type RepoCustomerTenants struct {
	mock.Mock
}

// GetCustomerTenants provides a mock function with given fields: application
func (_m *RepoCustomerTenants) GetCustomerTenants(application storage.JSONApplication) []platform.CustomerTenantInfo {
	ret := _m.Called(application)

	var r0 []platform.CustomerTenantInfo
	if rf, ok := ret.Get(0).(func(storage.JSONApplication) []platform.CustomerTenantInfo); ok {
		r0 = rf(application)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]platform.CustomerTenantInfo)
		}
	}

	return r0
}

// GetCustomerTenantsByEnvironment provides a mock function with given fields: application, environment
func (_m *RepoCustomerTenants) GetCustomerTenantsByEnvironment(application storage.JSONApplication, environment string) []platform.CustomerTenantInfo {
	ret := _m.Called(application, environment)

	var r0 []platform.CustomerTenantInfo
	if rf, ok := ret.Get(0).(func(storage.JSONApplication, string) []platform.CustomerTenantInfo); ok {
		r0 = rf(application, environment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]platform.CustomerTenantInfo)
		}
	}

	return r0
}
