// Code generated by mockery v2.9.4. DO NOT EDIT.

package purchaseorderapi

import (
	k8s "github.com/dolittle/platform-api/pkg/dolittle/k8s"
	mock "github.com/stretchr/testify/mock"

	platform "github.com/dolittle/platform-api/pkg/platform"

	purchaseorderapi "github.com/dolittle/platform-api/pkg/platform/microservice/purchaseorderapi"
)

// K8sResourceSpecFactory is an autogenerated mock type for the K8sResourceSpecFactory type
type K8sResourceSpecFactory struct {
	mock.Mock
}

// CreateAll provides a mock function with given fields: headImage, runtimeImage, k8sMicroservice, customerTenants, extra
func (_m *K8sResourceSpecFactory) CreateAll(headImage string, runtimeImage string, k8sMicroservice k8s.Microservice, customerTenants []platform.CustomerTenantInfo, extra platform.HttpInputPurchaseOrderExtra) purchaseorderapi.K8sResources {
	ret := _m.Called(headImage, runtimeImage, k8sMicroservice, customerTenants, extra)

	var r0 purchaseorderapi.K8sResources
	if rf, ok := ret.Get(0).(func(string, string, k8s.Microservice, []platform.CustomerTenantInfo, platform.HttpInputPurchaseOrderExtra) purchaseorderapi.K8sResources); ok {
		r0 = rf(headImage, runtimeImage, k8sMicroservice, customerTenants, extra)
	} else {
		r0 = ret.Get(0).(purchaseorderapi.K8sResources)
	}

	return r0
}
