// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// StorageProxy is an autogenerated mock type for the StorageProxy type
type StorageProxy struct {
	mock.Mock
}

// Delete provides a mock function with given fields: w, r, name
func (_m *StorageProxy) Delete(w http.ResponseWriter, r *http.Request, name string) {
	_m.Called(w, r, name)
}

// Download provides a mock function with given fields: w, name
func (_m *StorageProxy) Download(w http.ResponseWriter, name string) {
	_m.Called(w, name)
}

// Exists provides a mock function with given fields: w, name
func (_m *StorageProxy) Exists(w http.ResponseWriter, name string) {
	_m.Called(w, name)
}

// ListFiles provides a mock function with given fields: uriPrefix
func (_m *StorageProxy) ListFiles(uriPrefix string) ([]string, error) {
	ret := _m.Called(uriPrefix)

	var r0 []string
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(uriPrefix)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(uriPrefix)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Upload provides a mock function with given fields: w, r, name
func (_m *StorageProxy) Upload(w http.ResponseWriter, r *http.Request, name string) {
	_m.Called(w, r, name)
}
