// Code generated by mockery v2.9.4. DO NOT EDIT.

package git

import mock "github.com/stretchr/testify/mock"

// GitSync is an autogenerated mock type for the GitSync type
type GitSync struct {
	mock.Mock
}

// Pull provides a mock function with given fields:
func (_m *GitSync) Pull() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
