// Code generated by mockery v2.12.2. DO NOT EDIT.

package git

import (
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// GitSync is an autogenerated mock type for the GitSync type
type GitSync struct {
	mock.Mock
}

// Pull provides a mock function with given fields:
func (_m *GitSync) Pull() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewGitSync creates a new instance of GitSync. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewGitSync(t testing.TB) *GitSync {
	mock := &GitSync{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
