// Code generated by mockery v2.9.4. DO NOT EDIT.

package user

import (
	user "github.com/dolittle/platform-api/pkg/platform/user"
	mock "github.com/stretchr/testify/mock"
)

// KratosClientV5 is an autogenerated mock type for the KratosClientV5 type
type KratosClientV5 struct {
	mock.Mock
}

// AddCustomerToUser provides a mock function with given fields: _a0, customerID
func (_m *KratosClientV5) AddCustomerToUser(_a0 user.KratosUser, customerID string) error {
	ret := _m.Called(_a0, customerID)

	var r0 error
	if rf, ok := ret.Get(0).(func(user.KratosUser, string) error); ok {
		r0 = rf(_a0, customerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddCustomerToUserByEmail provides a mock function with given fields: email, customerID
func (_m *KratosClientV5) AddCustomerToUserByEmail(email string, customerID string) error {
	ret := _m.Called(email, customerID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(email, customerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddCustomerToUserByUserID provides a mock function with given fields: userID, customerID
func (_m *KratosClientV5) AddCustomerToUserByUserID(userID string, customerID string) error {
	ret := _m.Called(userID, customerID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(userID, customerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUser provides a mock function with given fields: id
func (_m *KratosClientV5) GetUser(id string) (user.KratosUser, error) {
	ret := _m.Called(id)

	var r0 user.KratosUser
	if rf, ok := ret.Get(0).(func(string) user.KratosUser); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(user.KratosUser)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByEmail provides a mock function with given fields: email
func (_m *KratosClientV5) GetUserByEmail(email string) (user.KratosUser, error) {
	ret := _m.Called(email)

	var r0 user.KratosUser
	if rf, ok := ret.Get(0).(func(string) user.KratosUser); ok {
		r0 = rf(email)
	} else {
		r0 = ret.Get(0).(user.KratosUser)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUsers provides a mock function with given fields:
func (_m *KratosClientV5) GetUsers() ([]user.KratosUser, error) {
	ret := _m.Called()

	var r0 []user.KratosUser
	if rf, ok := ret.Get(0).(func() []user.KratosUser); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user.KratosUser)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveCustomerToUserByEmail provides a mock function with given fields: email, customerID
func (_m *KratosClientV5) RemoveCustomerToUserByEmail(email string, customerID string) error {
	ret := _m.Called(email, customerID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(email, customerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateUser provides a mock function with given fields: _a0
func (_m *KratosClientV5) UpdateUser(_a0 user.KratosUser) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(user.KratosUser) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
