name: CI

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.18.3"

      - name: Build
        run: go build .

      - name: Test
        run: go test -v ./...

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          push: false
          context: .
          file: ./Dockerfile
