name: Pull request build and push

on:
  pull_request

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: docker/login-action@v1.14.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        run: go build .

      - name: Test
        run: go test -v ./...

      - name: Push PR Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: "."
          file: ./Dockerfile
          tags: dolittle/platform-api:${{ github.head_ref }}

  build-operations:
    runs-on: ubuntu-latest
    name: Build and Deploy platform-operations
    needs:
      - pull-request
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push PR Docker.Operations image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: "."
          file: ./Dockerfile.operations
          build-args: |
            BASE_IMAGE=dolittle/platform-api:${{ github.head_ref }}
          tags: dolittle/platform-operations:${{ github.head_ref }}