name: Pull request build and push

on: pull_request

jobs:
  reusable-workflow-test:
    uses: ./.github/workflows/update-configmap-field.yml
    secrets: inherit
    with:
      namespace: system-api
      name: dev-api-v1-env-variables
      field: GITHUB_WORKFLOW_TEST
      value: "test when dont be a environment"
  reusable-workflow-test-with-url:
    uses: ./.github/workflows/update-configmap-field.yml
    secrets: inherit
    with:
      environment: dev
      environment-url: https://example.com
      namespace: system-api
      name: dev-api-v1-env-variables
      field: GITHUB_WORKFLOW_TEST
      value: "test when dont be a environment"
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.16.3"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        run: go build .

      - name: Make output dir
        working-directory: ${{ env.SOURCE_PATH }}
        run: mkdir output

      - name: Run tests
        working-directory: ${{ env.SOURCE_PATH }}
        run: |
          go test ./... --coverprofile output/test-codecoverage.cov

      - name: Install Code Climate
        working-directory: ${{ env.SOURCE_PATH }}
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-0.10.1-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter

      - name: Report code coverage to Code Climate
        working-directory: ${{ env.SOURCE_PATH }}
        run: |
          ./cc-test-reporter format-coverage output/test-codecoverage.cov -t gocov -o output/test-codecoverage-codeclimate.json -p github.com/dolittle/platform-api
          CC_TEST_REPORTER_ID=${{ secrets.CC_TEST_REPORTER_ID }} \
          GIT_BRANCH=${{ env.GITHUB_REF }} \
          GIT_COMMIT=${{ env.GITHUB_SHA }} \
          ./cc-test-reporter \
          upload-coverage -i output/test-codecoverage-codeclimate.json

      - name: Push PR Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: "."
          file: ./Dockerfile
          tags: dolittle/platform-api:${{ github.head_ref }}

  build-operations:
    runs-on: ubuntu-latest
    name: Build and Deploy platform-operations
    needs:
      - pull-request
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push PR Docker.Operations image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: "."
          file: ./Dockerfile.operations
          build-args: |
            BASE_IMAGE=dolittle/platform-api:${{ github.head_ref }}
          tags: dolittle/platform-operations:${{ github.head_ref }}
