name: Update Container Image

on:
  workflow_call:
    inputs:
      namespace:
        description: 'Namespace of the deployment'
        required: true
        type: string
      deployment:
        description: 'Name of the deployment in k8s'
        required: true
        type: string
      container:
        description: 'Name of the container within the deployment, defaults to head'
        required: false
        default: head
        type: string
      image:
        required: true
        type: string
      environment:
        description: 'GitHub environment to run the job on, optional'
        required: false
        type: string
      enviroment-url:
        description:  'GitHub environments URL, can only be defined if environment is also defined, optional'
        required: false
        type: string
    secrets:
      K8S_CLUSTER_URL:
        required: true
      K8S_DEVOPS_SECRET:
        required: true
    
jobs:
  update:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: azure/k8s-set-context@v2
        with: 
          method: service-account
          k8s-url: ${{ secrets.K8S_CLUSTER_URL }}
          k8s-secret: ${{ secrets.K8S_DEVOPS_SECRET }}
      
      - name: Update deployment's image
        run: |
          kubectl -n ${{ inputs.namespace }} set image deployment/${{ inputs.deployment }} ${{ inputs.container }}=${{ inputs.image }}
        
