name: Update Configmaps Field

on:
  workflow_call:
    inputs:
      environment:
        description: 'GitHub environment to run the job on'
        required: false
        type: string
      enviroment-url:
        description:  'GitHub environments URL'
        required: false
        type: string
      namespace:
        description: 'Namespace of the deployment'
        required: true
        type: string
      name:
        description: 'Name of the configmap in k8s'
        required: true
        type: string
      field:
        description: 'Name of the field within the configmaps data property'
        required: true
        type: string
      value:
        description: 'Value to set to the field'
        required: true
        type: string
    secrets:
      K8S_CLUSTER_URL:
        required: true
      K8S_DEVOPS_SECRET:
        required: true
    
jobs:
  update:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment }}
      url: ${{ inputs.environment-url }}
    steps:
      - uses: azure/k8s-set-context@v2
        with: 
          method: service-account
          k8s-url: ${{ secrets.K8S_CLUSTER_URL }}
          k8s-secret: ${{ secrets.K8S_DEVOPS_SECRET }}

      - name: Create patch JSON
        id: create-patch-json
        run: |
          echo ::set-output name=patch_json::'{"data": { "${{ inputs.field }}": "${{ inputs.value }}" }}'

      - name: Update configmaps field
        run: |
          kubectl -n ${{ inputs.namespace }} patch configmap ${{ inputs.name }} --type merge -p '${{ steps.create-patch-json.outputs.patch_json }}'
