// Code generated by mockery v2.9.4. DO NOT EDIT.

package platform

import (
	platform "github.com/dolittle/platform-api/pkg/platform"
	mock "github.com/stretchr/testify/mock"
)

// Microservice is an autogenerated mock type for the Microservice type
type Microservice struct {
	mock.Mock
}

// GetBase provides a mock function with given fields:
func (_m *Microservice) GetBase() platform.MicroserviceBase {
	ret := _m.Called()

	var r0 platform.MicroserviceBase
	if rf, ok := ret.Get(0).(func() platform.MicroserviceBase); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(platform.MicroserviceBase)
	}

	return r0
}
